<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>BuyPolicy</description>
   <name>PolicyNo</name>
   <tag></tag>
   <elementGuidId>1f9ea572-0b1f-46dd-9503-10f3469cfdff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='quoteRecordsList']/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='quoteRecordsList']/tbody/tr[2]/td[3]</value>
   </webElementProperties>
</WebElementEntity>
