<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PremiumBreakup</description>
   <name>PremiumBreakUpButton</name>
   <tag></tag>
   <elementGuidId>d21f6800-dac2-4dd5-943e-5056aa90fba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@id='commissionBreakup_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[@id='commissionBreakup_0']</value>
   </webElementProperties>
</WebElementEntity>
