<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PolicyStartDate</description>
   <name>PolicyStartDate</name>
   <tag></tag>
   <elementGuidId>fdcc46b4-44d8-473f-a562-f8a030c5db7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='policy_start_date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='policy_start_date']</value>
   </webElementProperties>
</WebElementEntity>
