<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>PolicyTerm</description>
   <name>PolicyTerm</name>
   <tag></tag>
   <elementGuidId>a3d1daeb-dc3c-46e5-b522-9f710f74c31e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id=&quot;term_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id=&quot;term_id&quot;]</value>
   </webElementProperties>
</WebElementEntity>
