<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SelectBroker</description>
   <name>SelectBroker</name>
   <tag></tag>
   <elementGuidId>e6fcbca6-0193-4a5e-b83c-370d8456175c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@name=&quot;broker_id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@name=&quot;broker_id&quot;]</value>
   </webElementProperties>
</WebElementEntity>
