<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SelectProduct</description>
   <name>SelectProduct</name>
   <tag></tag>
   <elementGuidId>4ba84bca-d2cd-465c-8e4b-2e59ffdc2d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='product_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='product_id']</value>
   </webElementProperties>
</WebElementEntity>
