<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Renewal</description>
   <name>SearchProduct</name>
   <tag></tag>
   <elementGuidId>4d149361-670e-431a-b085-a38dfa4e244d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='gs_product_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='gs_product_name']</value>
   </webElementProperties>
</WebElementEntity>
