<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>ButtonSumit</description>
   <name>ButtonSubmit</name>
   <tag></tag>
   <elementGuidId>12b3147b-acbe-49f6-8d4b-52e35f849d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='form_submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='form_submit']</value>
   </webElementProperties>
</WebElementEntity>
