<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>SelectType</description>
   <name>SelectType</name>
   <tag></tag>
   <elementGuidId>943ef024-854a-48f6-a508-6e8f24d1a5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='Group234_Question427_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='Group234_Question427_0']</value>
   </webElementProperties>
</WebElementEntity>
