<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>BuyProcess</description>
   <name>MailTo</name>
   <tag></tag>
   <elementGuidId>82fb74ad-1b27-41a1-b91d-222e0d4fa22d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='mailTo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='mailTo']</value>
   </webElementProperties>
</WebElementEntity>
